# Generated by Django 4.1.7 on 2023-04-02 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_is_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='object',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
