# Generated by Django 4.1.7 on 2023-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_comment_post_comment_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object',
            new_name='post',
        ),
    ]
