# Generated by Django 4.1.6 on 2023-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_followrequest_accepted_alter_author_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False, max_length=500),
        ),
    ]
