# Generated by Django 4.1.6 on 2023-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.CharField(default={'items': [], 'type': 'followers'}, max_length=1000),
        ),
    ]
