# Generated by Django 4.1.6 on 2023-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0015_remove_author_friends_author_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.CharField(max_length=1000),
        ),
    ]
