# Generated by Django 4.1.6 on 2023-03-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_alter_followrequest_actor_alter_followrequest_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.CharField(default=[], max_length=1000),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.CharField(editable=False, max_length=1000),
        ),
    ]
