# Generated by Django 4.1.7 on 2023-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0020_alter_node_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
